### ISSUE TITLE
NodeBB constant crash with new update

### ISSUE THREAD

**Issue by tiimk** [yariplus/nodebb-plugin-minecraft-integration#100]
So  I have the minecraft server status widget and that seems to be crashing nodebb repeatdly. This is the error log:

 LOGS
{ avatarCDN: 'cravatar',
  customCDN: '',
  showDisplayNames: 0,
  debug: 0,
  avatarVariables: { size: 32, style: 'helmhead' },
  avatarExpiry: 60,
  pingExpiry: 365,
  showDisplayName: 0 }
4/11 23:21 [4879] - [31merror[39m: MongoError: skip requires an integer
    at Function.MongoError.create (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at Cursor.skip (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:610:49)
    at Object.module.getSortedSetRangeByLex (/home/tim/nodebb/nodebb/src/database/mongo/sorted.js:592:5)
    at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/api/status.js:136:16
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:726:13
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:52:16
    at done (/home/tim/nodebb/nodebb/node_modules/async/lib/async.js:246:17)
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:44:16
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:723:17
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:167:37
    at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/backend.js:213:5
    at handleCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
MongoError: skip requires an integer
    at Function.MongoError.create (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at Cursor.skip (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:610:49)
    at Object.module.getSortedSetRangeByLex (/home/tim/nodebb/nodebb/src/database/mongo/sorted.js:592:5)
    at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/api/status.js:136:16
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:726:13
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:52:16
    at done (/home/tim/nodebb/nodebb/node_modules/async/lib/async.js:246:17)
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:44:16
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:723:17
    at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:167:37
    at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/backend.js:213:5
    at handleCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
4/11 23:21 [4879] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
4/11 23:21 [4879] - [32minfo[39m: [app] Database connection closed.
4/11 23:21 [4879] - [32minfo[39m: [app] Web server closed to connections.
4/11 23:21 [4879] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (4879) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
4/11 23:21 [4918] - [32minfo[39m: Time: Fri Nov 04 2016 23:21:32 GMT-0400 (EDT)
4/11 23:21 [4918] - [32minfo[39m: Initializing NodeBB v1.2.1
4/11 23:21 [4918] - [32minfo[39m: [database] Checking database indices.
4/11 23:21 [4918] - [33mwarn[39m: [plugins/nodebb-plugin-minecraft-integration] Hook `filter:user.profileLinks` is deprecated, please use `filter:user.profileMenu` instead.
4/11 23:21 [4918] - [32minfo[39m: NodeBB Ready
4/11 23:21 [4918] - [32minfo[39m: Using ports 80 and 443 is not recommend; use a proxy instead. See README.md
4/11 23:21 [4918] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:80
LOGS CONTROL PANEL

**Comment by yariplus** [comment]
Thanks. I forgot I fixed this error in core already. It should be fixed on
master, or 1.3 should be out very soon.

On Nov 4, 2016 11:24 PM, "Tim Keckler" notifications@github.com wrote:

So I have the minecraft server status widget and that seems to be crashing
nodebb repeatdly. This is the error log:

LOGS
{ avatarCDN: 'cravatar',
customCDN: '',
showDisplayNames: 0,
debug: 0,
avatarVariables: { size: 32, style: 'helmhead' },
avatarExpiry: 60,
pingExpiry: 365,
showDisplayName: 0 }
4/11 23:21 [4879] - �[31merror�[39m: MongoError: skip requires an integer
at Function.MongoError.create (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
at Cursor.skip (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:
610:49)
at Object.module.getSortedSetRangeByLex (/home/tim/nodebb/nodebb/src/
database/mongo/sorted.js:592:5)
at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-
minecraft-integration/lib/api/status.js:136:16
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:726:13
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:52:16
at done (/home/tim/nodebb/nodebb/node_modules/async/lib/async.js:246:17)
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:44:16
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:723:17
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:167:37
at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-
minecraft-integration/lib/backend.js:213:5
at handleCallback (/home/tim/nodebb/nodebb/node_
modules/mongodb/lib/utils.js:96:12)
at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/collection.js:1357:5
at handleCallback (/home/tim/nodebb/nodebb/node_
modules/mongodb/lib/utils.js:96:12)
at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:661:5
at handleCallback (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
at nextFunction (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/
mongodb-core/lib/cursor.js:683:5)
at /home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/
mongodb-core/lib/cursor.js:585:7
at queryCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/
mongodb-core/lib/cursor.js:220:18)
at Callbacks.emit (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
at null.messageHandler (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
at Socket.<anonymous> (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/connection/
connection.js:302:22)
MongoError: skip requires an integer
at Function.MongoError.create (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
at Cursor.skip (/home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:
610:49)
at Object.module.getSortedSetRangeByLex (/home/tim/nodebb/nodebb/src/
database/mongo/sorted.js:592:5)
at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-
minecraft-integration/lib/api/status.js:136:16
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:726:13
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:52:16
at done (/home/tim/nodebb/nodebb/node_modules/async/lib/async.js:246:17)
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:44:16
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:723:17
at /home/tim/nodebb/nodebb/node_modules/async/lib/async.js:167:37
at /home/tim/nodebb/nodebb/node_modules/nodebb-plugin-
minecraft-integration/lib/backend.js:213:5
at handleCallback (/home/tim/nodebb/nodebb/node_
modules/mongodb/lib/utils.js:96:12)
at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/collection.js:1357:5
at handleCallback (/home/tim/nodebb/nodebb/node_
modules/mongodb/lib/utils.js:96:12)
at /home/tim/nodebb/nodebb/node_modules/mongodb/lib/cursor.js:661:5
at handleCallback (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
at nextFunction (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/
mongodb-core/lib/cursor.js:683:5)
at /home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/
mongodb-core/lib/cursor.js:585:7
at queryCallback (/home/tim/nodebb/nodebb/node_modules/mongodb/node_modules/
mongodb-core/lib/cursor.js:220:18)
at Callbacks.emit (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
at null.messageHandler (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
at Socket.<anonymous> (/home/tim/nodebb/nodebb/node_
modules/mongodb/node_modules/mongodb-core/lib/connection/
connection.js:302:22)
4/11 23:21 [4879] - �[32minfo�[39m: [app] Shutdown (SIGTERM/SIGINT)
Initialised.
4/11 23:21 [4879] - �[32minfo�[39m: [app] Database connection closed.
4/11 23:21 [4879] - �[32minfo�[39m: [app] Web server closed to connections.
4/11 23:21 [4879] - �[32minfo�[39m: [app] Shutdown complete.
[cluster] Child Process (4879) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
4/11 23:21 [4918] - �[32minfo�[39m: Time: Fri Nov 04 2016 23:21:32 GMT-0400
(EDT)
4/11 23:21 [4918] - �[32minfo�[39m: Initializing NodeBB v1.2.1
4/11 23:21 [4918] - �[32minfo�[39m: [database] Checking database indices.
4/11 23:21 [4918] - �[33mwarn�[39m:
[plugins/nodebb-plugin-minecraft-integration]
Hook filter:user.profileLinks is deprecated, please use
filter:user.profileMenu instead.
4/11 23:21 [4918] - �[32minfo�[39m: NodeBB Ready
4/11 23:21 [4918] - �[32minfo�[39m: Using ports 80 and 443 is not
recommend; use a proxy instead. See README.md
4/11 23:21 [4918] - �[32minfo�[39m: NodeBB is now listening on: 0.0.0.0:80
LOGS CONTROL PANEL

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/yariplus/nodebb-plugin-minecraft-integration/issues/100,
or mute the thread

**Comment by tiimk** [comment]
Haven't seen an update appear on nodebb for this yet :/

**Comment by yariplus** [comment]
Pushed a fix for 1.2

**Comment by yariplus** [comment]
This should no longer be an issue now that 1.3 is released.
