### ISSUE TITLE
NodeBB keeps restarting on startup after enabling the plugin

### ISSUE THREAD

**Issue by trexguo** [yariplus/nodebb-plugin-minecraft-integration#119]
Node version: 8.11.3
NodeBB version: 1.10.1
plugin version: 0.8.0-alpha.21

Here is the log:

```
2018-08-04T13:01:58.676Z [1757] - info: Initializing NodeBB v1.10.1 http://XXXXX
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2018-08-04T13:02:01.425Z [1757] - info: [socket.io] Restricting access to origin: http://XXXXX:*
2018-08-04T13:02:02.125Z [1757] - info: Routes added
2018-08-04T13:02:02.142Z [1757] - info: NodeBB Ready
2018-08-04T13:02:02.151Z [1757] - info: Enabling 'trust proxy'
2018-08-04T13:02:02.157Z [1757] - info: NodeBB is now listening on: 0.0.0.0:4567
{ avatarCDN: 'mojang',
  customCDN: '',
  showDisplayNames: 1,
  logLevel: 'info',
  avatarVariables: { size: 32, style: 'avatar' },
  avatarExpiry: 60,
  pingExpiry: 365,
  showDisplayName: 0 }
2018-08-04T13:02:08.865Z [1757] - error:  message=Cannot read property 'template' of undefined, stack=TypeError: Cannot read property 'template' of undefined
    at async.waterfall.translator.translate.next.html (/opt/nodebb/src/widgets/index.js:101:34)
    at nextTask (/opt/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/opt/nodebb/node_modules/async/dist/async.js:5331:9)
    at /opt/nodebb/node_modules/async/dist/async.js:969:16
    at /opt/nodebb/node_modules/async/dist/async.js:473:16
    at /opt/nodebb/node_modules/async/dist/async.js:2521:9
    at /opt/nodebb/node_modules/async/dist/async.js:473:16
    at replenish (/opt/nodebb/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/opt/nodebb/node_modules/async/dist/async.js:995:17)
    at /opt/nodebb/node_modules/async/dist/async.js:969:16
    at /opt/nodebb/node_modules/async/dist/async.js:2518:13
    at Timeout._nodebb.translator.translate.html [as _onTimeout] (/opt/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/widgets.js:63:50)
    at ontimeout (timers.js:502:15)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
2018-08-04T13:02:08.868Z [1757] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-08-04T13:02:08.883Z [1757] - info: [app] Web server closed to connections.
2018-08-04T13:02:08.888Z [1757] - info: [app] Database connection closed.
2018-08-04T13:02:08.889Z [1757] - info: [app] Shutdown complete.
[cluster] Child Process (1757) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-08-04T13:02:09.811Z [1780] - info: Initializing NodeBB v1.10.1 http://XXXX
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2018-08-04T13:02:12.032Z [1780] - info: [socket.io] Restricting access to origin: http://XXXXX:*
2018-08-04T13:02:12.514Z [1780] - info: Routes added
2018-08-04T13:02:12.526Z [1780] - info: NodeBB Ready
2018-08-04T13:02:12.532Z [1780] - info: Enabling 'trust proxy'
2018-08-04T13:02:12.537Z [1780] - info: NodeBB is now listening on: 0.0.0.0:4567
2018-08-04T13:02:14.239Z [1780] - error:  message=Cannot read property 'template' of undefined, stack=TypeError: Cannot read property 'template' of undefined
    at async.waterfall.translator.translate.next.html (/opt/nodebb/src/widgets/index.js:101:34)
    at nextTask (/opt/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/opt/nodebb/node_modules/async/dist/async.js:5331:9)
    at /opt/nodebb/node_modules/async/dist/async.js:969:16
    at /opt/nodebb/node_modules/async/dist/async.js:473:16
    at /opt/nodebb/node_modules/async/dist/async.js:2521:9
    at /opt/nodebb/node_modules/async/dist/async.js:473:16
    at replenish (/opt/nodebb/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/opt/nodebb/node_modules/async/dist/async.js:995:17)
    at /opt/nodebb/node_modules/async/dist/async.js:969:16
    at /opt/nodebb/node_modules/async/dist/async.js:2518:13
    at Timeout._nodebb.translator.translate.html [as _onTimeout] (/opt/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/widgets.js:63:50)
    at ontimeout (timers.js:502:15)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
2018-08-04T13:02:14.245Z [1780] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-08-04T13:02:14.254Z [1780] - info: [app] Web server closed to connections.
2018-08-04T13:02:14.256Z [1780] - info: [app] Database connection closed.
2018-08-04T13:02:14.256Z [1780] - info: [app] Shutdown complete.
[cluster] Child Process (1780) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-08-04T13:02:14.945Z [1801] - info: Initializing NodeBB v1.10.1 http://XXXX
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version

```

How do I fix this?
THANK YOU

**Comment by yariplus** [comment]
I'll take a look at it today. Standby.

**Comment by yariplus** [comment]
Pushed a new release. I think I fixed most of the errors. Only tested on bukkit. Let me know. Thanks.

https://github.com/yariplus/minecraft-nodebb-integration/releases/tag/v0.8.0-alpha.22

**Comment by yariplus** [comment]
fixed
