### ISSUE TITLE
Crashes on nodebb 0.7.x

### ISSUE THREAD

**Issue by Pilvinen** [yariplus/nodebb-plugin-minecraft-integration#50]
Malfunctions and throws errors and crashes Nodebb.

Missing error handler on `socket`.
TypeError: Object #<Object> has no method 'list'
    at SocketPlugins.mentions.listGroups (/home/minecraft/nodebb/node_modules/nodebb-plugin-custom-mentions/library.js:150:9)
    at callMethod (/home/minecraft/nodebb/src/socket.io/index.js:204:2)
    at onMessage (/home/minecraft/nodebb/src/socket.io/index.js:149:3)
    at Socket.<anonymous> (/home/minecraft/nodebb/src/socket.io/index.js:61:3)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.onevent (/home/minecraft/nodebb/node_modules/socketio-wildcard/index.js:17:17)
    at Socket.onpacket (/home/minecraft/nodebb/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/minecraft/nodebb/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/minecraft/nodebb/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/minecraft/nodebb/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)

11/8 01:12 [4661] - error: TypeError: Cannot call method 'split' of undefined
    at fullStatBack (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/backend.js:388:52)
    at /home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:177:16
    at deQueue (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:295:7)
    at Socket.<anonymous> (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:63:7)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)
TypeError: Cannot call method 'split' of undefined
    at fullStatBack (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/backend.js:388:52)
    at /home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:177:16
    at deQueue (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:295:7)
    at Socket.<anonymous> (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:63:7)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)
11/8 01:12 [4661] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
11/8 01:12 [4661] - info: [app] Database connection closed.
11/8 01:12 [4661] - info: [app] Web server closed to connections.
11/8 01:12 [4661] - info: [app] Shutdown complete.

**Comment by yariplus** [comment]
I think the version on npm is outdated, trying to fix it now.

**Comment by yariplus** [comment]
Seems that the package manager is busted.

Can you try upgrading from the command line?

In your nodebb directory do:
`npm i nodebb-plugin-minecraft-integration`

**Comment by Pilvinen** [comment]
It is still crashing the server after using "npm i nodebb-plugin-minecraft-integration" and activating the plugin from the manager restarting and adding a server from the settings:

[Minecraft Integration] [Aurinkomaa] Sending ServerListPing...
[Minecraft Integration] [Aurinkomaa] Sending ServerQuery...
11/8 11:55 [17360] - error: TypeError: Cannot read property 'split' of undefined
    at fullStatBack (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/updater.js:376:51)
    at /home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:177:16
    at deQueue (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:295:7)
    at Socket.<anonymous> (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:63:7)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
TypeError: Cannot read property 'split' of undefined
    at fullStatBack (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/updater.js:376:51)
    at /home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:177:16
    at deQueue (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:295:7)
    at Socket.<anonymous> (/home/minecraft/nodebb/node_modules/nodebb-plugin-minecraft-integration/node_modules/mcquery/lib/index.js:63:7)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
11/8 11:55 [17360] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
11/8 11:55 [17360] - info: [app] Database connection closed.
11/8 11:55 [17360] - info: [app] Web server closed to connections.
11/8 11:55 [17360] - info: [app] Shutdown complete.
3 restarts in 10 seconds, most likely an error on startup. Halting.

**Comment by yariplus** [comment]
Okay, I was able to reproduce the crash, latest should fix it. Do the `npm i` thing again and let me know. Thanks.

**Comment by Pilvinen** [comment]
It throws some errors but seems to work now.

**Comment by yariplus** [comment]
Cool. I haven't had much time to debug lately. If you could post any other errors it would help me a lot.

**Comment by yariplus** [comment]
Closing this, please create a new issue if you have any other errors or feature suggestions!

Thanks.
