### ISSUE TITLE
Add compatibility with MCPC+

### ISSUE THREAD

**Issue by popey456963** [yariplus/nodebb-plugin-minecraft-integration#87]
```
23:44:25 [WARNING] [NodeBB Integration] Task #44 for NodeBB Integration v0.6.2 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljava/util/Collection;
        at com.yaricraft.nodebbintegration.TaskTick$1.run(TaskTick.java:60)
        at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:332)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

This error repeats itself, with the task number increasing every so often.  The config.yml setup is:

```
FORUMURL: http://sinisterheavens.com/
FORUMNAME: Sinister Heavens
APIKEY: <secretAPIkey>
SOCKETNAMESPACE: plugins
PLUGINID: MinecraftIntegration
```

And the forum-side config is:

![](http://puu.sh/pYtdl/d6aba62fb3.png)

The server is running Java 7, Test Pack Please Ignore (1.6.4).  The NodeBB is running v1.0.3.

**Comment by yariplus** [comment]
Can you update to Java 8?

**Comment by popey456963** [comment]
Afraid not.  Java 8 isn't compatible with Test Pack, Please Ignore (whilst running MCPI or whatever the Bukkit version is called).

Is it required for this plugin?

**Comment by yariplus** [comment]
Yes, Java 8 is required.

It looks like there's no way to run Java 8 with mcpc. I tried a couple fixes but none of them worked.

Hmm, I think what I'll have to do is take Java 8 out of the core, Then I should be able to make a module for MCPC.

**Comment by yariplus** [comment]
Okay! This should work.

https://github.com/yariplus/minecraft-nodebb-integration/releases/download/v0.7.3/nodebb-integration-legacy-0.7.3.jar

Tested it with mcpc-plus-1.6.4-R2.1-forge965-B251.jar from yive's

**Comment by popey456963** [comment]
Wow, thanks for the incredibly quick reply.  This new Jar version does indeed produce no errors!  Which is great :+1:.  Alas, all is not green and I think I've found a new issue with this version.  I'll start a new issue though to keep things organised.
