### ISSUE TITLE
MC + Async == Crashes

### ISSUE THREAD

**Issue by ghostnegotiator** [yariplus/nodebb-plugin-minecraft-integration#92]
Apparently it does not like the Async plugin at all :(

```
21/9 18:25 [11122] - error: TypeError: undefined is not a function
    at _nodebb.SocketAdmin.MinecraftIntegration.(anonymous function) (/home/rdash/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/admin.js:48:7)
    at async.waterfall.err.message (/home/rdash/nodebb/src/socket.io/index.js:115:5)
    at fn (/home/rdash/nodebb/node_modules/async/lib/async.js:746:34)
    at /home/rdash/nodebb/node_modules/async/lib/async.js:1213:16
    at /home/rdash/nodebb/node_modules/async/lib/async.js:166:37
    at /home/rdash/nodebb/node_modules/async/lib/async.js:706:43
    at /home/rdash/nodebb/node_modules/async/lib/async.js:167:37
    at /home/rdash/nodebb/node_modules/async/lib/async.js:1209:30
    at /home/rdash/nodebb/src/socket.io/admin.js:45:11
    at /home/rdash/nodebb/src/database/mongo/sorted.js:402:4
    at handleCallback (/home/rdash/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/rdash/nodebb/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/home/rdash/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/rdash/nodebb/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at Socket.emit (events.js:95:17)
TypeError: undefined is not a function
    at _nodebb.SocketAdmin.MinecraftIntegration.(anonymous function) (/home/rdash/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/admin.js:48:7)
    at async.waterfall.err.message (/home/rdash/nodebb/src/socket.io/index.js:115:5)
    at fn (/home/rdash/nodebb/node_modules/async/lib/async.js:746:34)
    at /home/rdash/nodebb/node_modules/async/lib/async.js:1213:16
    at /home/rdash/nodebb/node_modules/async/lib/async.js:166:37
    at /home/rdash/nodebb/node_modules/async/lib/async.js:706:43
    at /home/rdash/nodebb/node_modules/async/lib/async.js:167:37
    at /home/rdash/nodebb/node_modules/async/lib/async.js:1209:30
    at /home/rdash/nodebb/src/socket.io/admin.js:45:11
    at /home/rdash/nodebb/src/database/mongo/sorted.js:402:4
    at handleCallback (/home/rdash/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/rdash/nodebb/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/home/rdash/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/rdash/nodebb/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/rdash/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at Socket.emit (events.js:95:17)
```

**Comment by ghostnegotiator** [comment]
Another crash output on refreshing the server:

```
21/9 18:29 [12100] - error: TypeError: Cannot read property 'name' of undefined
    at Request._callback (/home/rdash/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/utils.js:112:41)
    at Request.self.callback (/home/rdash/nodebb/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/rdash/nodebb/node_modules/request/request.js:1048:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/rdash/nodebb/node_modules/request/request.js:969:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
TypeError: Cannot read property 'name' of undefined
    at Request._callback (/home/rdash/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/utils.js:112:41)
    at Request.self.callback (/home/rdash/nodebb/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/rdash/nodebb/node_modules/request/request.js:1048:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/rdash/nodebb/node_modules/request/request.js:969:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
```

**Comment by yariplus** [comment]
What is triggering the first error? or does it seem to appear at random?

**Comment by ghostnegotiator** [comment]
It seems to be triggered on refreshing server status.

**Comment by yariplus** [comment]
Weird, those functions are indeed undefined, but nothing should be calling them. Wasn't able to reproduce.

I pushed a version to define those functions, and an extra error check for the second one, but it looks like the package manager hasn't updated yet.

**Comment by ghostnegotiator** [comment]
I will see if I can break it again later today.

What I I do use node v6.6.0 now by the way.

**Comment by yariplus** [comment]
Okay, it should be updated now.

Node version shouldn't affect this issue, but it's good you updated, the next version of nbb requires v4+

**Comment by ghostnegotiator** [comment]
Heya, did not had time to check it out. But will give a followup soon after
I've ipdated it.

**Comment by yariplus** [comment]
Re-open if still an issue.
