### ISSUE TITLE
Crashing on user registration

### ISSUE THREAD

**Issue by tiimk** [yariplus/nodebb-plugin-minecraft-integration#93]
Everytime I attempt to register I get this error in Nodebb and it causes it to crash. Same thing happens if I try to reset my API key. 

Got "/register" command from Minecraft server 0.
Player TheTkeck is attempting to register with player key ETdJJHED58cOczw4DbUhGbccHnFYOTpHvqugaciV4mQgC63XEPY5av02OraLkr8m
22/10 19:34 [9472] - [31merror[39m: ReferenceError: API is not defined
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/api/users.js:49:5
    at /home/nodebb/nodebb/src/database/mongo/sorted.js:113:4
    at handleCallback (/home/nodebb/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/nodebb/nodebb/node_modules/mongodb/lib/collection.js:1196:5
    at commandCallback (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1246:9)
    at Callbacks.emit (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
ReferenceError: API is not defined
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-minecraft-integration/lib/api/users.js:49:5
    at /home/nodebb/nodebb/src/database/mongo/sorted.js:113:4
    at handleCallback (/home/nodebb/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/nodebb/nodebb/node_modules/mongodb/lib/collection.js:1196:5
    at commandCallback (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1246:9)
    at Callbacks.emit (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/nodebb/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
22/10 19:34 [9472] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
22/10 19:34 [9472] - [32minfo[39m: [app] Database connection closed.
22/10 19:34 [9472] - [32minfo[39m: [app] Web server closed to connections.
22/10 19:34 [9472] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (9472) has exited (code: 1, signal: null)

**Comment by yariplus** [comment]
Thanks, should be fixed now.

There's probably a lot of bugs with the current version (alpha) right now, feel free to report them as they come up. :+1:
